version: 0.1

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y software-properties-common
      - add-apt-repository ppa:openjdk-r/ppa
      - apt-get update -y
      - apt-get install -y openjdk-8-jdk
      - apt-get install -y maven
  pre_build:
    commands:
      - echo This is pre_build
      - echo Logging in to Amazon ECR...
      - aws ecr get-login --no-include-email --region us-east-1
      - export MAVEN_OPTS='-Xmx512m -XX:MaxPermSize=128m'
  build:
    commands:
      - echo Starting build 'date'
      - echo Build started on 'date'
      - echo Building the Docker image...
      - sudo docker -v
      - sudo docker run hello-world
      - mvn install 
      - sudo dockerd -D
      - sudo docker build -t dasbootregistry:latest .
      - sudo docker tag dasbootregistry:latest 889894765174.dkr.ecr.us-east-1.amazonaws.com/dasbootregistry:latest
  post_build:
    commands:
      - echo Build completed on 'date'
      - echo Pushing the Docker image...
      - sudo docker push dasbootregistry:latest 
      - sudo service docker stop
artifacts:
  files:
    - target/Das-Boot-App.jar
discard-paths: yes
