version: 0.2
phases:
  build:
    commands:
    - echo Build started on 'date'
    - mvn clean package
  post_build:
    commands:
    - echo Build completed on 'date'
artifacts:
  files:
    - /target/Das-Boot-App.jar
