version: 0.1
environment_variables:
  plaintext:
    JAVA_HOME: "/usr/java/jdk-8u141-linux-x64"
phases:
  install:
    commands:
      - cd /usr
      - mkdir java
      - cd java
      - wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" https://edelivery.oracle.com/otn-pub/java/jdk/8u141-b15/336fa29ff2bb4ef291e347e091f7f4a7/jdk-8u141-linux-x64.rpm 
      - yum install jdk-8u141-linux-x64.rpm
      - apt-get update -y
      - apt-get install -y maven
  pre_build:
    commands:
      - echo This is pre_build
  build:
    commands:
      - echo Starting build `date`
      - mvn clean package
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/Das-Boot-App.jar
discard-paths: yes
