version: 0.2

phases:
  build:
    commands:
      - sudo groupadd docker
      - sudo usermod -aG docker user
      - docker build -f Dockerfile -t dasbootregistry .
      - docker images
  post_build:
    commands:
      - eval 'aws ecr get-login --region us-east-1'
      - docker tag dasbootregistry:latest 889894765174.dkr.ecr.us-east-1.amazonaws.com/dasbootregistry:latest
      - docker push 889894765174.dkr.ecr.us-east-1.amazonaws.com/dasbootregistry:latest 
