version: 0.1

phases:
  build:
    commands:
      - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      - sudo apt-get update
      - apt-cache policy docker-ce
      - sudo apt-get install -y docker-ce
      - sudo systemctl status docker
      - docker build -f Dockerfile -t dasbootregistry .
      - docker images
  post_build:
    commands:
      - eval 'aws ecr get-login --region us-east-1'
      - docker tag dasbootregistry:latest 889894765174.dkr.ecr.us-east-1.amazonaws.com/dasbootregistry:latest
      - docker push 889894765174.dkr.ecr.us-east-1.amazonaws.com/dasbootregistry:latest 
