version: 0.1
environment_variables:
  plaintext:
    JAVA_HOME: "/opt/openjdk-8-jdk"
phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y openjdk-8-jdk
      - apt-get install -y maven
  pre_build:
    commands:
      - echo This is pre_build
  build:
    commands:
      - echo Starting build `date`
      - mvn clean package
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/Das-Boot-App.jar
discard-paths: yes
