version: 0.1

phases:
  build:
    commands:
      - sudo systemctl start docker
      - docker build -t dasbootregistry .
     
  post_build:
    commands:
      - eval 'aws ecr get-login --region us-east-1'
      - docker tag dasbootregistry:latest 889894765174.dkr.ecr.us-east-1.amazonaws.com/dasbootregistry:latest
      - docker push 889894765174.dkr.ecr.us-east-1.amazonaws.com/dasbootregistry:latest 
