version: 0.1

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y software-properties-common
      - add-apt-repository ppa:openjdk-r/ppa
      - apt-get update -y
      - apt-get install -y openjdk-8-jdk
      - apt-get install -y maven
      - sudo apt-get install curl -y
      - curl -sSL https://get.docker.com/ | sh
      - sudo dockerd -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock &
  pre_build:
    commands:
      - echo This is pre_build
      - echo Logging in to Amazon ECR...
      - aws ecr get-login --no-include-email --region us-east-1
  build:
    commands:
      - echo Starting build 'date'
      - mvn clean package install
      - echo Build started on 'date'
      - echo Building the Docker image...
      - mvn install -DpushImageTag
      - mvn install Dockerfile:build -DpushImageTag
      - sudo docker build -t dasbootregistry:latest .
      - sudo docker tag dasbootregistry:latest 080204196416.dkr.ecr.us-east-1.amazonaws.com/dasbootregistry:latest
  post_build:
    commands:
      - echo Build completed on 'date'
      - echo Pushing the Docker image...
      - sudo docker push dasbootregistry:latest 
      - sudo service docker stop
artifacts:
  files:
    - target/Das-Boot-App.jar
discard-paths: yes
